#!/bin/bash -e

export FCGI_SOCKET_PATH="$FCGI_HOST:$FCGI_SOAP_PORT" 

# Sleep so that main Sympa process can start and prepare everything
sleep 10

exec chpst -u sympa:sympa /usr/bin/spawn-fcgi -p "$FCGI_SOAP_PORT" /usr/local/lib/sympa/cgi/sympa_soap_server-wrapper.fcgi &
