#!/bin/bash -e

export FCGI_SOCKET_PATH="$FCGI_HOST:$FCGI_PORT"

# Sleep so that main Sympa process can start and prepare everything
sleep 10

exec chpst -u sympa:sympa /usr/local/lib/sympa/cgi/wwsympa.fcgi 2>&1
